{{ $moduleSettings := index .Values "module-settings" }}
{{ $moduleSettingsMonitor := $moduleSettings.metrics.serviceMonitor.enabled}}
{{- range $module, $spec := .Values.install -}}
{{- $specMetrics := $spec.metrics -}}
{{- $specMetricsService := $specMetrics.service -}}
{{- $specServiceMonitor := $specMetrics.serviceMonitor -}}
{{- if and $spec.enabled $spec.metrics.enabled }}
{{- if or $.Values.global.enableServiceMonitors $specServiceMonitor $moduleSettingsMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "conduit-helm.fullname" $ }}-{{ default $module $moduleSettings.metrics.serviceMonitor.name $specServiceMonitor.name }}
  {{- if $specServiceMonitor.namespace }}
  namespace: {{ $specServiceMonitor.namespace }}
  {{- else if $moduleSettings.metrics.serviceMonitor.namespace }}
  namespace: {{ $moduleSettings.metrics.serviceMonitor.namespace}}
  {{- end }}
  labels:
{{ include "conduit-helm.labels" $ | indent 4 }}
    app: {{ template "conduit-helm.fullname" $ }}-{{ $module }}
    release: {{ template "conduit-helm.fullname" $ }}
    {{- if $moduleSettings.metrics.serviceMonitor.selector }}
      {{- toYaml $moduleSettings.metrics.serviceMonitor.selector | nindent 4 }}
    {{- end }}
    {{- if $specServiceMonitor.selector }}
      {{- toYaml $specServiceMonitor.selector  | nindent 4 }}
    {{- end }}
    {{- if $moduleSettings.metrics.serviceMonitor.additionalLabels }}
      {{- toYaml $moduleSettings.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
    {{- if $specServiceMonitor.additionalLabels }}
      {{- toYaml $specServiceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
{{ include "conduit-helm.selectorLabels" $ | indent 6 }}
      app: {{ template "conduit-helm.fullname" $ }}-{{ $module }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: {{ default $moduleSettings.metrics.service.name $specMetricsService.name }}
      path: /metrics
      {{- if $specServiceMonitor.interval }}
      interval: {{ $specServiceMonitor.interval }}
      {{- else if $moduleSettings.metrics.serviceMonitor.interval }}
      interval: {{ $moduleSettings.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if $specServiceMonitor.relabelings }}
      relabelings:
        {{- toYaml $specServiceMonitor.relabelings | nindent 8 }}
      {{- else if $moduleSettings.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml $moduleSettings.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if $specServiceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml $specServiceMonitor.metricRelabelings | nindent 8 }}
      {{- else if $moduleSettings.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml $moduleSettings.metrics.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if $specServiceMonitor.scheme }}
      scheme: {{ $specServiceMonitor.scheme }}
      {{- else if $moduleSettings.metrics.serviceMonitor.scheme }}
      scheme: {{ $moduleSettings.metrics.serviceMonitor.scheme }}
      {{- end }}
      {{- if $specServiceMonitor.tlsConfig  }}
      tlsConfig:
        {{- toYaml $specServiceMonitor.tlsConfig | nindent 8 }}
      {{- else if $moduleSettings.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml $moduleSettings.metrics.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
