{{ $moduleSettings := index .Values "module-settings" }}
{{- range $module, $spec := .Values.install -}}
{{- $specService := $spec.service -}}
{{- $specMetrics := $spec.metrics -}}
{{- $specMetricsService := $spec.metrics.service -}}
{{- $appName := include "conduit-helm.resourceName" (dict "prefix" (include "conduit-helm.fullname" $) "suffix" $module) }}
{{- $headlessName := include "conduit-helm.resourceName" (dict "prefix" (include "conduit-helm.fullname" $) "suffix" (printf "%s-headless" $module)) }}
{{- if $spec.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $headlessName }}
  labels:
{{ include "conduit-helm.labels" $ | indent 4 }}
    app: {{ $appName }}
  {{- if $moduleSettings.service.labels }}
    {{- toYaml $moduleSettings.service.labels | nindent 4 }}
  {{- end }}
  {{- if $spec.service }}
  {{- if $spec.service.labels }}
    {{- toYaml $spec.service.labels | nindent 4 }}
  {{- end }}
  {{- end }}
  annotations:
{{ include "conduit-helm.chartAnnotations" $ | indent 4 }}
  {{- if $moduleSettings.service.annotations }}
    {{- toYaml $moduleSettings.service.annotations | nindent 4 }}
  {{- end }}
  {{- if $spec.service }}
  {{- if $spec.service.annotations }}
    {{- toYaml $spec.service.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
{{ include "conduit-helm.selectorLabels" $ | indent 4 }}
    app: {{ $appName }}
  ports:
    - protocol: TCP
      port: {{ coalesce $specService.grpc_port $spec.containerPort $moduleSettings.containerPort $.Values.global.config.grpc_port }}
      name: tcp
      targetPort: {{ coalesce $specService.grpc_port $spec.containerPort $moduleSettings.containerPort $.Values.global.config.grpc_port }}
{{- if $spec.metrics.enabled }}
    - port: {{ default $moduleSettings.metrics.service.port $specMetricsService.port }}
      name: {{ default $moduleSettings.metrics.service.name $specMetricsService.name }}
      targetPort: {{ default $moduleSettings.metrics.service.targetPort $specMetricsService.targetPort }}
{{- end }}
{{- end }}
{{- end }}
