{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "conduit-helm.serviceAccountName" . }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
rules:
{{- with .Values.rbac.rules }}
{{ toYaml . | indent 2 }}
{{- else }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}
