apiVersion: v1
kind: ConfigMap
metadata:
  name: conduit-admin-cm
data:
  CONDUIT_API: {{ template "conduit-helm.conduit.api" . }}
  CONDUIT_URL: {{ template "conduit-helm.conduit.url" . }}
  {{- if or .Values.prometheus.setup .Values.externalPrometheus.url }}
  PROMETHEUS_URL: {{ template "conduit-helm.prometheus.url" . }}
  {{- end }}
  