{{- if not .Values.global.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduit-helm.secretName" . }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  MASTER_KEY: {{ template "conduit-helm.master_key" . }}
  {{- if .Values.global.secret.grpc_enable }}
  GRPC_KEY: {{ template "conduit-helm.grpc_key" . }}
  {{- end }}
{{- end }}
