apiVersion: v1
kind: Secret
metadata:
  name: conduit-secret
data:
  MASTER_KEY: {{ template "conduit-helm.master_key" . }}
  {{- if .Values.global.secret.grpc_enable }}
  GRPC_KEY: {{ template "conduit-helm.grpc_key" . }}
  {{- end }}
