apiVersion: v1
kind: ConfigMap
metadata:
  name: conduit-cm
data:
  METRICS_PORT: {{ .Values.global.config.metrics_port | quote }}
  CONDUIT_SERVER: {{ template "conduit-helm.core.fullname" . }}:{{ .Values.core.service.grpc_port }}
  {{- if or .Values.loki.setup .Values.externalLoki.url }}
  LOKI_URL: {{ template "conduit-helm.loki.url" . }}
  {{- end }}
