{{- if and .Values.externalRedis.host .Values.externalRedis.password (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduit-helm.resourceName" (dict "prefix" (include "conduit-helm.fullname" .) "suffix" "redis") }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
  {{- with .Values.externalRedis.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | b64enc }}
{{- end }}
