apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.core.fullname" . }}
  annotations:
    {{- with .Values.core.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.core.fullname" . }}
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
{{ include "conduit-helm.selectorLabels" . | indent 6 }}
      app: {{ template "conduit-helm.core.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.labels" . | indent 8 }}
        app: {{ template "conduit-helm.core.fullname" . }}
      {{- if .Values.core.podLabels }}
        {{- toYaml .Values.core.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.core.podAnnotations }}
      annotations:
        {{- toYaml .Values.core.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "conduit-helm.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if (not .Values.externalRedis.host ) }}
      initContainers:
        - name: wait-for-redis
          image: goodsmileduck/redis-cli
          imagePullPolicy: IfNotPresent
          args: [ 'sh', '-c', 'until redis-cli  -h {{ template "conduit-helm.redis.fullname" . }} -p {{ .Values.redis.port }}  get hello; do echo "Sleeping a bit"; sleep 1; done; echo "ready!"; ' ]
      {{- end }}
      {{- with .Values.core.initContainers }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Values.core.name }}
          image: {{ default .Values.global.image.repository .Values.core.image.repository }}/{{ .Values.core.image.name }}:{{ default .Values.global.image.tag .Values.core.image.tag }}
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.core.image.imagePullPolicy }}
          command:
            {{- with .Values.core.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- with .Values.core.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: conduit-cm
            - secretRef:
                name: conduit-secret
            {{- with .Values.core.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            grpc:
              port: {{ default .Values.global.config.grpc_port .Values.core.containerPort  }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: {{ default .Values.global.config.grpc_port .Values.core.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: __DEFAULT_HOST_URL
              value: {{ template "conduit-helm.core.default_host" . }}
            - name: CONDUIT_NAMESPACE
              value: {{ .Release.Namespace }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: {{ template "conduit-helm.redis.fullname" . }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            {{- else if and .Values.externalRedis.host .Values.externalRedis.port }}
            - name: REDIS_HOST
              value: {{ .Values.externalRedis.host }}
            - name: REDIS_PORT
              value: {{ .Values.externalRedis.port | quote }}
            {{- end }}
            - name: GRPC_PORT
              value: {{ default .Values.global.config.grpc_port .Values.core.containerPort | quote }}
            {{- with .Values.core.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with .Values.core.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.core.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- with .Values.core.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
