apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.core.fullname" . }}
  annotations:
{{ include "conduit-helm.chartAnnotations" . | indent 4 }}
    {{- with .Values.core.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.core.fullname" . }}
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
{{ include "conduit-helm.selectorLabels" . | indent 6 }}
      app: {{ template "conduit-helm.core.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.podLabels" (dict "root" . "app" (include "conduit-helm.core.fullname" .) "extra" .Values.core.podLabels) | indent 8 }}
      {{- if .Values.core.podAnnotations }}
      annotations:
        {{- toYaml .Values.core.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "conduit-helm.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- include "conduit-helm.podSecurityContext" (dict "root" . "component" .Values.core) | nindent 6 }}
      {{- $waitForRedis := not .Values.externalRedis.host }}
      {{- if or $waitForRedis .Values.core.initContainers }}
      initContainers:
        {{- if $waitForRedis }}
        - name: wait-for-redis
          image: {{ include "conduit-helm.image" (dict "repository" .Values.core.waitForRedis.image.repository "tag" .Values.core.waitForRedis.image.tag "digest" .Values.core.waitForRedis.image.digest) }}
          imagePullPolicy: {{ .Values.core.waitForRedis.image.pullPolicy }}
          {{- include "conduit-helm.containerSecurityContext" (dict "root" . "component" dict) | nindent 10 }}
          args: [ 'sh', '-c', 'until nc -z {{ template "conduit-helm.redis.fullname" . }} {{ .Values.redis.port }}; do echo "waiting for redis"; sleep 2; done; echo "ready!"' ]
        {{- end }}
        {{- with .Values.core.initContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.core.name }}
          image: {{ include "conduit-helm.appImage" (dict "root" . "component" .Values.core) }}
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.core.image.imagePullPolicy }}
          command:
            {{- with .Values.core.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- with .Values.core.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- include "conduit-helm.containerSecurityContext" (dict "root" . "component" .Values.core) | nindent 10 }}
          envFrom:
            - configMapRef:
                name: conduit-cm
            - secretRef:
                name: {{ include "conduit-helm.secretName" . }}
            {{- with .Values.core.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- $readiness := default (dict) .Values.core.readinessProbe }}
          {{- $liveness := default (dict) .Values.core.livenessProbe }}
          readinessProbe:
            grpc:
              port: {{ default .Values.global.config.grpc_port .Values.core.containerPort  }}
            initialDelaySeconds: {{ default $.Values.global.probes.readiness.initialDelaySeconds $readiness.initialDelaySeconds }}
            periodSeconds: {{ default $.Values.global.probes.readiness.periodSeconds $readiness.periodSeconds }}
            timeoutSeconds: {{ default $.Values.global.probes.readiness.timeoutSeconds $readiness.timeoutSeconds }}
            successThreshold: {{ default $.Values.global.probes.readiness.successThreshold $readiness.successThreshold }}
            failureThreshold: {{ default $.Values.global.probes.readiness.failureThreshold $readiness.failureThreshold }}
          livenessProbe:
            grpc:
              port: {{ default .Values.global.config.grpc_port .Values.core.containerPort }}
            initialDelaySeconds: {{ default $.Values.global.probes.liveness.initialDelaySeconds $liveness.initialDelaySeconds }}
            periodSeconds: {{ default $.Values.global.probes.liveness.periodSeconds $liveness.periodSeconds }}
            timeoutSeconds: {{ default $.Values.global.probes.liveness.timeoutSeconds $liveness.timeoutSeconds }}
            successThreshold: {{ default $.Values.global.probes.liveness.successThreshold $liveness.successThreshold }}
            failureThreshold: {{ default $.Values.global.probes.liveness.failureThreshold $liveness.failureThreshold }}
          env:
            - name: __DEFAULT_HOST_URL
              value: {{ template "conduit-helm.core.default_host" . }}
            - name: CONDUIT_NAMESPACE
              value: {{ .Release.Namespace }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: {{ template "conduit-helm.redis.fullname" . }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            {{- else if and .Values.externalRedis.host .Values.externalRedis.port }}
            - name: REDIS_HOST
              value: {{ .Values.externalRedis.host }}
            - name: REDIS_PORT
              value: {{ .Values.externalRedis.port | quote }}
            {{- if or .Values.externalRedis.existingSecret .Values.externalRedis.password }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "conduit-helm.redis.passwordSecretName" . }}
                  key: redis-password
            {{- end }}
            {{- end }}
            - name: GRPC_PORT
              value: {{ default .Values.global.config.grpc_port .Values.core.containerPort | quote }}
            {{- with .Values.core.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with .Values.core.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.core.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- with .Values.core.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "conduit-helm.podScheduling" (dict "root" . "component" .Values.core) | nindent 6 }}
