{{ $moduleSettings := index .Values "module-settings" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "conduit-helm.core.fullname" . }}-headless
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.core.fullname" . }}
  {{- if .Values.core.service.labels }}
    {{- toYaml .Values.core.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.core.service.annotations }}
  annotations:
    {{- toYaml .Values.core.service.annotations | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
{{ include "conduit-helm.selectorLabels" . | indent 4 }}
    app: {{ template "conduit-helm.core.fullname" . }}
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      name: tcp
    - protocol: TCP
      port: {{ default .Values.global.config.grpc_port .Values.core.containerPort }}
      targetPort: {{ default .Values.global.config.grpc_port .Values.core.containerPort }}
      name: grpc
    - protocol: TCP
      port: 3031
      targetPort: 3031
      name: socket
{{- if .Values.core.metrics.enabled }}
    - port: {{ .Values.global.config.metrics_port }}
      name: {{ .Values.core.metrics.service.name }}
      targetPort:  {{ .Values.global.config.metrics_port }}
{{- end }}
