{{- $coreName := include "conduit-helm.core.fullname" . -}}
{{- if .Values.core.metrics.enabled }}
{{- if or .Values.global.enableServiceMonitors .Values.core.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ default $coreName .Values.core.metrics.serviceMonitor.name }}
  {{- if .Values.core.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.core.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ $coreName }}
    release: {{ template "conduit-helm.fullname" . }}
    {{- with .Values.core.metrics.serviceMonitor.selector }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.core.metrics.serviceMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
{{ include "conduit-helm.selectorLabels" . | indent 6 }}
      app: {{ $coreName }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port:  {{ .Values.core.metrics.service.name }}
      path: /metrics
      {{- with .Values.core.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.core.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.metrics.serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with .Values.core.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
