{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.admin.fullname" . }}
  annotations:
    {{- with .Values.admin.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
{{ include "conduit-helm.selectorLabels" . | indent 6 }}
      app: {{ template "conduit-helm.admin.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.labels" . | indent 8 }}
        app: {{ template "conduit-helm.admin.fullname" . }}
      {{- if .Values.admin.podLabels }}
        {{- toYaml .Values.admin.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.podAnnotations }}
      annotations:
        {{- toYaml .Values.admin.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.admin.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name:  {{ .Values.admin.name }}
          image: {{ default .Values.global.image.repository .Values.admin.image.repository }}/{{ .Values.admin.image.name }}:{{ default .Values.global.image.tag .Values.admin.image.tag }} 
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.admin.image.imagePullPolicy }}
          command:
            {{- with .Values.admin.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- with .Values.admin.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}  
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: conduit-admin-cm
            {{- with .Values.admin.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: conduit-secret
                  key: MASTER_KEY
            {{- if or .Values.loki.setup .Values.externalLoki.url }}
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: conduit-cm
            {{- end }}
            {{- with .Values.admin.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with .Values.admin.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.admin.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}     
      volumes:
        {{- with .Values.admin.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
            