{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.admin.fullname" . }}
  annotations:
{{ include "conduit-helm.chartAnnotations" . | indent 4 }}
    {{- with .Values.admin.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
{{ include "conduit-helm.selectorLabels" . | indent 6 }}
      app: {{ template "conduit-helm.admin.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.podLabels" (dict "root" . "app" (include "conduit-helm.admin.fullname" .) "extra" .Values.admin.podLabels) | indent 8 }}
      {{- if .Values.admin.podAnnotations }}
      annotations:
        {{- toYaml .Values.admin.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- include "conduit-helm.podSecurityContext" (dict "root" . "component" .Values.admin) | nindent 6 }}
      {{- with .Values.admin.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name:  {{ .Values.admin.name }}
          image: {{ include "conduit-helm.appImage" (dict "root" . "component" .Values.admin) }}
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.admin.image.imagePullPolicy }}
          command:
            {{- with .Values.admin.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- with .Values.admin.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- include "conduit-helm.containerSecurityContext" (dict "root" . "component" .Values.admin) | nindent 10 }} 
          ports:
            - containerPort: 8080
          {{- $readiness := default (dict) .Values.admin.readinessProbe }}
          {{- $liveness := default (dict) .Values.admin.livenessProbe }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ default $.Values.global.probes.readiness.initialDelaySeconds $readiness.initialDelaySeconds }}
            periodSeconds: {{ default $.Values.global.probes.readiness.periodSeconds $readiness.periodSeconds }}
            timeoutSeconds: {{ default $.Values.global.probes.readiness.timeoutSeconds $readiness.timeoutSeconds }}
            successThreshold: {{ default $.Values.global.probes.readiness.successThreshold $readiness.successThreshold }}
            failureThreshold: {{ default $.Values.global.probes.readiness.failureThreshold $readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ default $.Values.global.probes.liveness.initialDelaySeconds $liveness.initialDelaySeconds }}
            periodSeconds: {{ default $.Values.global.probes.liveness.periodSeconds $liveness.periodSeconds }}
            timeoutSeconds: {{ default $.Values.global.probes.liveness.timeoutSeconds $liveness.timeoutSeconds }}
            successThreshold: {{ default $.Values.global.probes.liveness.successThreshold $liveness.successThreshold }}
            failureThreshold: {{ default $.Values.global.probes.liveness.failureThreshold $liveness.failureThreshold }}
          envFrom:
            - configMapRef:
                name: conduit-admin-cm
            {{- with .Values.admin.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: CONDUIT_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "conduit-helm.secretName" . }}
                  key: MASTER_KEY
            {{- if or .Values.loki.setup .Values.externalLoki.url }}
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: conduit-cm
            {{- end }}
            {{- with .Values.admin.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with .Values.admin.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.admin.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}     
      volumes:
        {{- with .Values.admin.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "conduit-helm.podScheduling" (dict "root" . "component" .Values.admin) | nindent 6 }}
{{- end }}
            