{{- if and .Values.admin.enabled .Values.admin.ingress.enabled }}
{{- $extraPaths := .Values.admin.ingress.extraPaths -}}
apiVersion: {{ include "conduit-helm.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "conduit-helm.admin.fullname" . }}
  annotations:
    {{- with .Values.admin.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
spec:
  {{- if eq (include "conduit-helm.ingress.apiVersion" $) "networking.k8s.io/v1" }}
  {{- with .Values.admin.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.admin.ingress.hostName }} 
      http:
        paths:
          - path: /
            {{- if eq (include "conduit-helm.ingress.apiVersion" $) "networking.k8s.io/v1" }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if eq (include "conduit-helm.ingress.apiVersion" $) "networking.k8s.io/v1" }}
              service:
                name:  {{ template "conduit-helm.admin.fullname" . }}
                port:
                  number: {{ .Values.admin.service.http_port }}
              {{- else }}
              serviceName:  {{ template "conduit-helm.admin.fullname" . }}
              servicePort: {{ .Values.admin.service.http_port }}
              {{- end }}
          {{ if $extraPaths }}
          {{ toYaml $extraPaths | indent 10 }}
          {{- end }}
  {{- if .Values.admin.ingress.tls }}
  tls:
    {{- toYaml .Values.admin.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
