{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "conduit-helm.admin.fullname" . }}
  labels:
    app: {{ template "conduit-helm.admin.fullname" . }}
{{ include "conduit-helm.labels" . | indent 4 }}
  {{- if .Values.admin.service.labels }}
    {{- toYaml .Values.admin.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.admin.service.annotations }}
  annotations:
    {{- toYaml .Values.admin.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
{{ include "conduit-helm.selectorLabels" . | indent 4 }}
    app: {{ template "conduit-helm.admin.fullname" . }}
  ports:
    - port: {{ .Values.admin.service.http_port }}
      name: http
      targetPort: 8080
      {{- if eq .Values.admin.service.type "NodePort" }}
      nodePort: {{ .Values.admin.service.nodePort }}
      {{- end }}
  type: {{ .Values.admin.service.type }}
{{- if eq .Values.admin.service.type "LoadBalancer" }}
{{- if .Values.admin.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.admin.service.loadBalancerIP | quote }}
{{- end }}
{{- end }}
{{- end }}
