apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.database.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.database.fullname" . }}
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
{{ include "conduit-helm.selectorLabels" . | indent 6 }}
      app: {{ template "conduit-helm.database.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.labels" . | indent 8 }}
        app: {{ template "conduit-helm.database.fullname" . }}
      {{- if .Values.database.podLabels }}
        {{- toYaml .Values.database.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.database.podAnnotations }}
      annotations:
        {{- toYaml .Values.database.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.database.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Values.database.name }}
          image: {{ default .Values.global.image.repository .Values.database.image.repository }}/{{ .Values.database.image.name }}:{{ default .Values.global.image.tag .Values.database.image.tag }} 
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.database.image.imagePullPolicy }}
          command:
            {{- with .Values.database.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- with .Values.database.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}  
          ports:
            - containerPort: {{ default .Values.global.config.grpc_port .Values.database.containerPort }}
          envFrom:
            - configMapRef:
                name: conduit-cm
            - secretRef:
                name: conduit-database-secret
            {{- with .Values.database.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: SERVICE_URL
              value: {{ template "conduit-helm.database.fullname" . }}:{{ .Values.database.service.tcp_port }}
            - name: CONDUIT_NAMESPACE
              value: {{ .Release.Namespace }}
            {{- if .Values.global.secret.grpc_enable }}
            - name: GRPC_KEY
              valueFrom:
                secretKeyRef:
                  name: conduit-secret
                  key: GRPC_KEY
            {{- end }}
            - name: GRPC_PORT
              value: {{ default .Values.global.config.grpc_port .Values.database.containerPort | quote }}
            {{- with .Values.database.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with .Values.database.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.database.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- with .Values.database.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
            
