{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.redis.fullname" . }} 
  annotations:
    {{- with .Values.redis.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
  labels:
    app: {{ template "conduit-helm.redis.fullname" . }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ template "conduit-helm.redis.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.labels" . | indent 8 }}
        app: {{ template "conduit-helm.redis.fullname" . }}
      {{- if .Values.redis.podLabels }}
        {{- toYaml .Values.redis.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml .Values.redis.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image.name }}:{{ .Values.redis.image.tag }} 
          imagePullPolicy: {{ .Values.redis.image.imagePullPolicy }}
          command:
            {{- with .Values.redis.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          {{- with .Values.redis.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.redis.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.redis.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- with .Values.redis.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}

