{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.redis.fullname" . }} 
  annotations:
{{ include "conduit-helm.chartAnnotations" . | indent 4 }}
    {{- with .Values.redis.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.redis.fullname" . }}
spec:
  replicas: {{ .Values.redis.replicas }}
  strategy:
    type: {{ .Values.redis.strategy.type }}
  selector:
    matchLabels:
      app: {{ template "conduit-helm.redis.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.podLabels" (dict "root" . "app" (include "conduit-helm.redis.fullname" .) "extra" .Values.redis.podLabels) | indent 8 }}
      {{- if .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml .Values.redis.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- include "conduit-helm.podSecurityContext" (dict "root" . "component" .Values.redis) | nindent 6 }}
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ include "conduit-helm.image" (dict "repository" .Values.redis.image.name "tag" .Values.redis.image.tag "digest" .Values.redis.image.digest) }}
          imagePullPolicy: {{ .Values.redis.image.imagePullPolicy }}
          {{- include "conduit-helm.containerSecurityContext" (dict "root" . "component" .Values.redis) | nindent 10 }}
          command:
            {{- if .Values.redis.extraArgs }}
              {{- toYaml .Values.redis.extraArgs | nindent 12 }}
            {{- else if .Values.redis.persistence.enabled }}
            - redis-server
            - "--appendonly"
            - "yes"
            - "--appendfsync"
            - "everysec"
            {{- end }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          {{- with .Values.redis.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.redis.persistence.enabled }}
            - name: redis-data
              mountPath: /data
            {{- end }}
            {{- with .Values.redis.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.redis.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.redis.persistence.enabled }}
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "conduit-helm.resourceName" (dict "prefix" (include "conduit-helm.redis.fullname" .) "suffix" "data") }}
        {{- end }}
        {{- with .Values.redis.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "conduit-helm.podScheduling" (dict "root" . "component" .Values.redis) | nindent 6 }}
{{- end }}

