{{- if .Values.mongodb.enabled  -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conduit-helm.mongodb.fullname" . }} 
  annotations:
    {{- with .Values.mongodb.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
  labels:
    app: {{ template "conduit-helm.mongodb.fullname" . }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ template "conduit-helm.mongodb.fullname" . }}
  template:
    metadata:
      labels:
{{ include "conduit-helm.labels" . | indent 8 }}
        app: {{ template "conduit-helm.mongodb.fullname" . }}
      {{- if .Values.mongodb.podLabels }}
        {{- toYaml .Values.mongodb.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.mongodb.podAnnotations }}
      annotations:
        {{- toYaml .Values.mongodb.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.mongodb.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Values.mongodb.name }}
          image: {{ .Values.mongodb.image.name }}:{{ .Values.mongodb.image.tag }} 
          imagePullPolicy: {{ .Values.mongodb.image.imagePullPolicy }}
          command:
            {{- with .Values.mongodb.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          {{- with .Values.mongodb.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mongodb.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.mongodb.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.mongodb.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- with .Values.mongodb.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}