{{- if .Values.mongodb.enabled  -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "conduit-helm.mongodb.fullname" . }} 
  labels:
{{ include "conduit-helm.labels" . | indent 4 }}
    app: {{ template "conduit-helm.mongodb.fullname" . }} 
  {{- if .Values.mongodb.service.labels }}
    {{- toYaml .Values.mongodb.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.mongodb.service.annotations }}
  annotations:
    {{- toYaml .Values.mongodb.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
{{ include "conduit-helm.selectorLabels" . | indent 4 }}
    app: {{ template "conduit-helm.mongodb.fullname" . }} 
  ports:
    - port: {{ .Values.mongodb.port }}
      name: {{ .Values.mongodb.name }}
  type: ClusterIP
{{- end }}

